### ISSUE TITLE
scTDA.RootedGraph With groups=FALSE not working

### ISSUE THREAD

**Issue by csbbcompbio** [pcamara/scTDA#8]
Dear Pablo,
Hope you are doing fine. I am trying to run scTDA on one of our datasets and I am facing this error:
total of 616 patches required clustering
this implies 1693 nodes in the mapper graph
Traceback (most recent call last):
  File "scTDA_Tutorial.py", line 161, in <module>
    c = scTDA.RootedGraph('Embryo_pca_25_0.40', 'Embryo.no_subsampling.tsv', groups=False)
  File "/Users/pra7mx/anaconda/lib/python2.7/site-packages/scTDA/main.py", line 1531, in __init__
    self.g3, self.dicdend = self.dendritic_graph()
  File "/Users/pra7mx/anaconda/lib/python2.7/site-packages/scTDA/main.py", line 1503, in dendritic_graph
    dil = networkx.shortest_path_length(self.gl, self.root, k)
  File "/Users/pra7mx/anaconda/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/generic.py", line 245, in shortest_path_length
    p=nx.bidirectional_shortest_path(G,source,target)
  File "/Users/pra7mx/anaconda/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 136, in bidirectional_shortest_path
    results=_bidirectional_pred_succ(G,source,target)
  File "/Users/pra7mx/anaconda/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 186, in _bidirectional_pred_succ
    for w in Gsucc(v):
  File "/Users/pra7mx/anaconda/lib/python2.7/site-packages/networkx/classes/graph.py", line 1084, in neighbors_iter
    raise NetworkXError("The node %s is not in the graph." % (n,))
networkx.exception.NetworkXError: The node 0 is not in the graph.

Can you please help me with this.

Thanks,

Cheers !!

Praneet

**Comment by csbbcompbio** [comment]
I have also updated the scTDA version and tried and still error is coming up.

**Comment by pcamara** [comment]
Dear Praneet,

Thanks for pointing this out. I need more information to be able to understand what is going on. Could you please send me the input tables and the offending command so that I can reproduce the error on my side?

Thanks,

Pablo

**Comment by csbbcompbio** [comment]
Hi Pablo,
Here I have attached the files I am using and also the command thats giving me the error.
[E8_1.txt](https://github.com/pcamara/scTDA/files/1270697/E8_1.txt)
[data.txt](https://github.com/pcamara/scTDA/files/1270702/data.txt)


"c = scTDA.RootedGraph('Embryo_pca_25_0.40', 'Embryo.no_subsampling.tsv', groups=False)"


Thanks,

Cheers !!
Praneet

**Comment by leungchuenyan** [comment]
Dear Pablo, 

Many thanks for creating this package and the nice tutorial. I am getting a similar error as the previous post.. I wonder if there was a fix to it? I think I have the most recent scTDA by installing from https://github.com/CamaraLab/scTDA.git

Many thanks in advance !!!

Best wishes,
CY

>>> c = scTDA.RootedGraph('test_pca_25_0.40', 'test.no_subsampling.tsv', groups=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/labuser/anaconda2/lib/python2.7/site-packages/scTDA/main.py", line 1536, in __init__
    self.g3, self.dicdend = self.dendritic_graph()
  File "/Users/labuser/anaconda2/lib/python2.7/site-packages/scTDA/main.py", line 1508, in dendritic_graph
    dil = networkx.shortest_path_length(self.gl, self.root, k)
  File "/Users/labuser/anaconda2/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/generic.py", line 244, in shortest_path_length
    raise nx.NodeNotFound("Source {} not in G".format(source))
networkx.exception.NodeNotFound: Source 0 not in G
>>>
